name: bivalenz_world_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0-323.2.beta

dependencies:
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  logic_expr_tree:
    path: ../logic_expr_tree

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
